<script lang="ts">
	import type { LayoutProps } from './$types';

	let { data, children }: LayoutProps = $props();
</script>

<div class="mb-4 w-full border-b border-gray-300 p-1">
	<span class="ml-4">DEADWEB</span>
	<span class="ml-4 text-red-500">This site was generated by AI</span>
	<a href="/">Home</a>
</div>
{@render children()}
